// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA50s70J-kgoGlqk7uShlxhrLFIuYNWmNc',
    appId: '1:614828687448:web:e2c68de78cd67e502a8a2d',
    messagingSenderId: '614828687448',
    projectId: 'noteapp-71346',
    authDomain: 'noteapp-71346.firebaseapp.com',
    storageBucket: 'noteapp-71346.appspot.com',
    measurementId: 'G-SPMQNQD16N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVVI8AkOREdf_6WzNcPU0ki_stySZ5C4c',
    appId: '1:614828687448:android:a0453a71333f87bf2a8a2d',
    messagingSenderId: '614828687448',
    projectId: 'noteapp-71346',
    storageBucket: 'noteapp-71346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU9Qhv_EdzujwLZgdzfxyZYJkHwXYL32Q',
    appId: '1:614828687448:ios:aa8e49ccf2b59df52a8a2d',
    messagingSenderId: '614828687448',
    projectId: 'noteapp-71346',
    storageBucket: 'noteapp-71346.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU9Qhv_EdzujwLZgdzfxyZYJkHwXYL32Q',
    appId: '1:614828687448:ios:7d70074a8d4eda012a8a2d',
    messagingSenderId: '614828687448',
    projectId: 'noteapp-71346',
    storageBucket: 'noteapp-71346.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
